#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys
# from pyxel.editor import run
from pyxel.editor import App
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    # sys.exit(run())
    App(("new.pyxres" if len(sys.argv) == 1 else sys.argv[1]))
